### ISSUE TITLE
Re-execute function for `useTable`

### ISSUE THREAD

**Issue by Mause** [ar1a/react-supabase-fp#2]
I noticed you left a TODO in your code here: https://github.com/ar1a/react-supabase-fp/blob/cad721476f7580ece8d08b5a377bb631ef3674ea/src/hooks/useTable.ts#L54

I've been playing around with Supabase and decided to try out your library and have been finding it pretty nice, but this functionality is currently missing sadly :(

**Comment by Mause** [comment]
Just refreshing a list of data post insert/update is where I'm hoping to use it?

Unfortunately looks like some of the types were broken in 1.1.0:

```
node_modules/react-supabase-fp/src/context/context.ts(8,14): semantic error TS2742: The inferred type of 'SupabaseContext' cannot be named without a reference to 'react-supabase-fp/node_modules/@types/react'. This is likely not portable. A type annotation is necessary.
```
https://github.com/Mause/financial-dash/pull/48/checks?check_run_id=3308278911

**Comment by ar1a** [comment]
ah, I think I need to make supabase-js a peer dependency. I'll update it
soon and let you know!!

**Comment by ar1a** [comment]
this should be fixed in https://github.com/ar1a/react-supabase-fp/commit/1bffbf627c9480eb08e2c1f0aaf2c92c74fa0e72

i've bumped to 1.1.1 and updated the @next tag on npm. try it out and let me know!

**Comment by Mause** [comment]
@ar1a No luck I'm afraid, same error :(

https://github.com/Mause/financial-dash/pull/48/checks?check_run_id=3309275281

**Comment by ar1a** [comment]
Alright, another attempt to fix in 955d582099f8ba6c97ec41c2358b518091bb1742

same deal, 1.1.2 and tag has been updated.

sorry for the hassle :/

**Comment by Mause** [comment]
Hah, it's all good, this is just a hobby project 💜

```
node_modules/react-supabase-fp/src/hooks/useTable.ts(62,28): semantic error TS2571: Object is of type 'unknown'.
```
Here -> https://github.com/ar1a/react-supabase-fp/blob/23d64afef6c671aa26d20a87fa9154d746522ced/src/hooks/useTable.ts#L62
Different error this time! Progress!

https://github.com/Mause/financial-dash/pull/48/checks?check_run_id=3309439046

**Comment by ar1a** [comment]
62 should actually be this line... https://github.com/ar1a/react-supabase-fp/blob/f31af9ead01c73c3f9b3fc3ef8e3a23f768656d9/src/hooks/useTable.ts#L62

there is no reason why supabase should be unknown, `useSupabase` returns an `Option<SupabaseClient>`

honestly, kinda stumped here. i think it might be something with your ci or my peer dependencies setup? ive not worked with them much before.

if you see it fails earlier here https://github.com/Mause/financial-dash/pull/48/checks?check_run_id=3309439046#step:4:34

which would explain why there are no types for supabase

i cloned your project, checked out the branch and ran `yarn --frozen`. works fine on my machine

i think if this goes where i think it will, my previous changes are also unnecessary

**Comment by ar1a** [comment]
please check out the new version! i think i have solved your ci problem :)

**Comment by Mause** [comment]
Yep, all solved now

For the future -> https://github.com/npm/rfcs/blob/latest/implemented/0025-install-peer-deps.md
